# Generated by Django 3.1.7 on 2021-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='EC1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='EC2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='EC3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
