# Generated by Django 3.1.7 on 2021-06-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20210616_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='appointmentP',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('bookedon', models.DateField(auto_now_add=True)),
                ('date', models.DateField()),
                ('how', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.patient')),
            ],
        ),
    ]
