# Generated by Django 3.2.6 on 2021-10-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
